apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # llama-serve resources
  - ../../../llama-serve/granite-8b
  - ../../../mcp-servers/slack-mcp

patchesStrategicMerge:
  - remove-tavily-env.yaml
